todo-aspnetmvc-ui/Models/ErrorViewModel.cs
namespace todo_aspnetmvc_ui.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

todo-aspnetmvc-ui/Models/ViewModels/PagingInfo.cs
using System;

namespace todo_aspnetmvc_ui.Models.ViewModels
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }
        public int ItemsPerPage { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages => (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage);
    }
}

todo-aspnetmvc-ui/Models/ViewModels/ToDoItemsViewModel.cs
using System.Collections.Generic;
using System.Linq;
using todo_domain_entities;

namespace todo_aspnetmvc_ui.Models.ViewModels
{
    public class ToDoItemsViewModel
    {
        public IEnumerable<IGrouping<ToDoList, ToDoEntry>> GroupedToDoItems { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string SelectedDueDate { get; set; }
    }
}

todo-aspnetmvc-ui/Models/ViewModels/ToDoListsViewModel.cs
using System.Collections.Generic;
using todo_domain_entities;

namespace todo_aspnetmvc_ui.Models.ViewModels
{
    public class ToDoListsViewModel
    {
        public IEnumerable<ToDoList> ToDoLists { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public SummaryOfToDoLists SummaryOfToDoLists { get; set; }
        public bool ShowHiddenToDoLists { get; set; } = true;
        public bool ShowCompletedTasks { get; set; } = true;
    }
}

todo-aspnetmvc-ui/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using todo_aspnetmvc_ui.Infrastructure;
using todo_aspnetmvc_ui.Models;
using todo_aspnetmvc_ui.Models.Services;
using todo_aspnetmvc_ui.Models.ViewModels;

namespace todo_aspnetmvc_ui.Controllers
{
    public class HomeController : Controller
    {
        private readonly IToDoServices _toDoServices;
        public const int PageSize = 5;

        public HomeController(IToDoServices toDoServices)
        {
            _toDoServices = toDoServices ?? throw new ArgumentNullException(nameof(toDoServices));
        }

        public ViewResult Index(string duedate, int page = 1)
        {
            if (duedate == null)
            {
                duedate = ToDoItemsDueDate.DueDateToday.GetAttribute<DisplayAttribute>().Name;
            }

            var dueDateAsEnum = duedate.GetValueFromName<ToDoItemsDueDate>();
            var (selectedItems, count) = _toDoServices.GetGroupedToDoItemsByDueDate(
                dueDateAsEnum,
                PageSize,
                page);

            return View(new ToDoItemsViewModel
            {
                GroupedToDoItems = selectedItems,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = count,
                },
                SelectedDueDate = dueDateAsEnum.GetAttribute<DisplayAttribute>().Name
            });
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

todo-aspnetmvc-ui/Controllers/ToDoListsController.cs
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using todo_aspnetmvc_ui.Models.Services;
using todo_aspnetmvc_ui.Models.ViewModels;
using todo_domain_entities;

namespace todo_aspnetmvc_ui.Controllers
{
    public class ToDoListsController : Controller
    {
        private readonly IToDoServices _todoServices;
        public const int PageSize = 3;

        public ToDoListsController(IConfiguration configuration, IToDoServices todoServices)
        {
            _todoServices = todoServices ?? throw new ArgumentNullException(nameof(todoServices));
        }


        [HttpGet]
        public ActionResult Index(int page = 1)
        {
            var showHiddenToDoLists = bool.Parse(HttpContext.Request.Cookies["ShowHiddenToDoLists"] ?? "True");
            var showCompletedTasks = bool.Parse(HttpContext.Request.Cookies["ShowCompletedTasks"] ?? "True");
            var (todoLists, count) = showHiddenToDoLists
                            ? _todoServices.GetToDoLists(PageSize, page)
                            : _todoServices.GetVisibleToDoLists(PageSize, page);

            return View(new ToDoListsViewModel
            {
                ToDoLists = todoLists,
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = count,
                },
                SummaryOfToDoLists = _todoServices.GetSummaryOfToDoLists(),
                ShowHiddenToDoLists = showHiddenToDoLists,
                ShowCompletedTasks = showCompletedTasks
            });
        }

        [HttpPost]
        public ActionResult UpdateGeneralList(bool showHiddenLists, bool showCompletedTasks)
        {
            HttpContext.Response.Cookies.Append("ShowHiddenToDoLists", showHiddenLists.ToString());
            HttpContext.Response.Cookies.Append("ShowCompletedTasks", showCompletedTasks.ToString());

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult OpenToDoList(int toDoListId)
        {
            var todoList = _todoServices.GetToDoListById(toDoListId);

            if (todoList != null)
            {
                return View(todoList);
            }

            return NotFound();
        }

        [HttpPost]
        public ActionResult CreateToDoList(string newTodoListTitle)
        {
            var listId = _todoServices.AddToDoList(new ToDoList { MainTitle = newTodoListTitle }).Id;

            return RedirectToAction(nameof(OpenToDoList), new { toDoListId = listId });
        }

        [HttpPost]
        public ActionResult DeleteToDoList(ToDoList toDoList)
        {
            _todoServices.RemoveToDoList(toDoList.Id);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult EditToDoListTitle(ToDoList toDoList)
        {
            _todoServices.ModifyToDoList(toDoList.Id, toDoList);

            return RedirectToAction(nameof(OpenToDoList), new { toDoListId = toDoList.Id });
        }

        [HttpPost]
        public void ChangeVisiblityState(int todoListId)
        {
            _todoServices.ChangeVisiblityOfToDoList(todoListId);
        }

        [HttpPost]
        public string ChangeToDoStatus(int todoItemId)
        {
            return _todoServices.ChangeToDoItemsStatus(todoItemId);
        }

        [HttpPost]
        public ActionResult AddToDoItem(ToDoEntry toDoItem, int todoListId)
        {
            try
            {
                _todoServices.AddToDoItemToList(toDoItem, todoListId);

                return RedirectToAction(nameof(OpenToDoList), new { toDoListId = toDoItem.ToDoList.Id });
            }
            catch(ArgumentException)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        [HttpPost]
        public ActionResult EditToDoItem(ToDoEntry toDoItem, int todoListId)
        {
            toDoItem.ToDoList = _todoServices.GetToDoListById(todoListId);
            _todoServices.ModifyToDoEntry(toDoItem.Id, toDoItem);

            return RedirectToAction(nameof(OpenToDoList), new { toDoListId = toDoItem.ToDoList.Id });
        }

        [HttpPost]
        public ActionResult DeleteToDoItem(ToDoEntry toDoItem, int todoListId)
        {
            _todoServices.RemoveToDoEntry(toDoItem.Id);

            return RedirectToAction(nameof(OpenToDoList), new { toDoListId = todoListId });
        }
    }
}

todo-aspnetmvc-ui/Infrastructure/ToDoItemsNavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using todo_aspnetmvc_ui.Models.Services;

namespace todo_aspnetmvc_ui.Infrastructure
{
    public class ToDoItemsNavigationMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var dueDateTypes = new List<string>();

            foreach (var value in Enum.GetValues(typeof(ToDoItemsDueDate)))
            {
                dueDateTypes.Add(((ToDoItemsDueDate)value).GetAttribute<DisplayAttribute>().Name);
            }

            if (ViewBag.SelectedDueDate == null)
            {
                ViewBag.SelectedDueDate = dueDateTypes.FirstOrDefault();
            }

            return View(dueDateTypes);
        }
    }
}

todo-aspnetmvc-ui/Views/Home/Index.cshtml
@model ToDoItemsViewModel

@{
    ViewBag.SelectedDueDate = Model.SelectedDueDate;
}


<div class="row m-1 p-1">
    <div id="categories" class="col-auto">

        <h5>View tasks by due date</h5>
        <vc:to-do-items-navigation-menu />
    </div>
    <div class="col" style="background-color:azure">
        @if (Model.GroupedToDoItems.Count() != 0)
        {
            @foreach (var list in Model.GroupedToDoItems)
            {

                <h6>
                    ToDo list:
                    <a asp-controller="ToDoLists" asp-action="OpenToDoList" asp-route-toDoListId="@list.Key.Id">
                        @list.Key.MainTitle
                    </a>
                </h6>

                <partial name="_ToDoItems" model="@list.OrderBy(entry => entry.OrdinalNumber)" />
                <br />
            }
        }
        else
        {
            <p class="fs-4 fw-lighter text-center">
                No uncompleted tasks
            </p>
        }

        @if (Model.PagingInfo.TotalPages > 1)
        {
            <pagenav page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true"
                     page-class="page-link" page-class-normal="page-item" page-class-selected="page-item active"
                     page-url-duedate="@Model.SelectedDueDate">
            </pagenav>
        }
    </div>
</div>

todo-aspnetmvc-ui/Views/Shared/Components/ToDoItemsNavigationMenu/Default.cshtml
@model IEnumerable<string>

<div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
    @foreach (var dueDate in Model)
    {
        <a class="nav-link@(dueDate == ViewBag.SelectedDueDate ? " active": "")" id="v-pills-@dueDate-tab" 
           data-toggle="pill" asp-action="Index" asp-controller="Home" role="tab" 
           aria-controls="v-pills-@dueDate" asp-route-duedate="@dueDate" asp-route-page="1"
           aria-selected="@(dueDate == ViewBag.SelectedDueDate ? true : false)">
            @dueDate</a>
    }
</div>

todo-aspnetmvc-ui/Views/Shared/_ToDoItems.cshtml
@using todo_aspnetmvc_ui.Infrastructure
@using System.ComponentModel.DataAnnotations;

@model IEnumerable<ToDoEntry>

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Due date</th>
                <th scope="col">Status</th>
                <th scope="col">Description</th>
                <th scope="col">Notes</th>
                <th> </th>
            </tr>
        </thead>

        <tbody>
            @foreach (var todoItem in Model)
            {
                var dueDateInDays = (todoItem.DueDate.Value.Date - DateTime.Now.Date).TotalDays;
                string dueDateInDaysToView = "today";

                if (dueDateInDays > 0)
                {
                    dueDateInDaysToView = $"in {dueDateInDays} " + (dueDateInDays != 1 ? "days" : "day");
                }
                else if (dueDateInDays < 0)
                {
                    dueDateInDaysToView = $"{dueDateInDays * -1} " + (dueDateInDays != -1 ? "days" : "day") + " overdue";
                }
                <tr>
                    <th>@todoItem.OrdinalNumber</th>
                    <td>@todoItem.Title</td>
                    <td>
                        <div class="col">
                            <div class="row">
                                @todoItem.DueDate.Value.ToString("dd.MM.yyyy H:mm")
                            </div>
                            @if (todoItem.Status != ToDoStatus.Completed)
                            {
                                <div class="row">
                                    (@dueDateInDaysToView)
                                </div>
                            }
                        </div>
                    </td>
                    <td>
                        @if (todoItem.Status == ToDoStatus.NotStarted)
                        {
                            <img id="statusImg@(todoItem.Id)" width="20" src="~/img/icons/status-not-started.png">
                        }
                        else if (todoItem.Status == ToDoStatus.InProgress)
                        {
                            <img id="statusImg@(todoItem.Id)" width="20" src="~/img/icons/status-in-progress.png">
                        }
                        else
                        {
                            <img id="statusImg@(todoItem.Id)" width="20" src="~/img/icons/status-completed.png">
                        }
                        <span id="statusSpan@(todoItem.Id)">
                            @(todoItem.Status.GetAttribute<DisplayAttribute>().Name)
                        </span>
                    </td>
                    <td>@(string.IsNullOrEmpty(todoItem.Description) ? "-" : todoItem.Description)</td>
                    <td>@(string.IsNullOrEmpty(todoItem.Notes) ? "-" : todoItem.Notes)</td>

                    <td>
                        @if (todoItem.Status == ToDoStatus.NotStarted)
                        {
                            <input id="statusBtn@(todoItem.Id)" type="button" value="Start" class="btn btn-outline-success btn-sm"
                                   onclick="processState(@todoItem.Id, '@Url.Action("ChangeToDoStatus", "ToDoLists")')" />

                        }
                        else if (todoItem.Status == ToDoStatus.InProgress)
                        {
                            <input id="statusBtn@(todoItem.Id)" type="button" value="Complete" class="btn btn-outline-success btn-sm"
                                   onclick="processState(@todoItem.Id, '@Url.Action("ChangeToDoStatus", "ToDoLists")')" />
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

todo-aspnetmvc-ui/Views/Shared/_TopNavigationMenu.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                <div class="h-25 w-25 d-inline" >
                    <img src="~/img/icons/logo.jpg" class="img-fluid" width="50">
                    <span>TODO APPLICATION</span>
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex" >
                <ul class="navbar-nav flex-grow-2">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="ToDoLists" asp-action="Index">TODO Lists</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

todo-aspnetmvc-ui/Views/ToDoLists/Index.cshtml
@{
    Layout = "_ToDoListsLayout";
}

@using Newtonsoft.Json;
@using todo_aspnetmvc_ui.Infrastructure
@using System.ComponentModel.DataAnnotations;

@model ToDoListsViewModel

<div class="row m-1 p-1" style="background: whitesmoke">
    <div id="todosummary" class="col-auto">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="textbox" aria-orientation="vertical">
            <partial name="_ToDoListsSummary" model="Model" />
        </div>
        <br />
    </div>
    <div class="col">
        <div class="col-3 col-md-5">
            <form method="post" asp-action="CreateToDoList" asp-controller="ToDoLists" autocomplete="off">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" name="newTodoListTitle" placeholder="ToDo list title" aria-label="ToDo list title" required>
                    <input type="submit" class="btn btn-success" value="Create list" />
                </div>
            </form>
            <form asp-controller="ToDoLists" asp-action="UpdateGeneralList" id="listsUpdateForm">
                <div class="row">
                    <div class="col-auto">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="showHidedListsChecked" asp-for="@Model.ShowHiddenToDoLists"
                                   onclick="updateList()" name="showHiddenLists">
                            <label class="form-check-label" for="showHidedListsChecked">
                                Show hidden lists (@Model.SummaryOfToDoLists.HiddenToDoListsCount)
                            </label>
                        </div>
                    </div>
                    <div class="col-auto">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="showCompletedTasksChecked" asp-for="@Model.ShowCompletedTasks"
                                   onclick="updateList()" name="showCompletedTasks">
                            <label class="form-check-label" for="showCompletedTasksChecked">Show completed tasks in lists</label>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="accordion mb-0" id="todoListsPaging">
            @foreach (var todoList in Model.ToDoLists)
            {
                <div class="accordion-item" style="background:azure">
                    <h2 class="accordion-header" id="heading@(todoList.Id)">
                        <button class="accordion-button collapsed" type="button" style="font-weight: bold" data-bs-toggle="collapse" data-bs-target="#name@(todoList.Id)" aria-expanded="false" aria-controls="name@(todoList.Id)">
                            @todoList.MainTitle | @(todoList.Status.GetAttribute<DisplayAttribute>().Name)
                        </button>
                    </h2>
                    <div id="name@(todoList.Id)" class="accordion-collapse collapse" aria-labelledby="heading@(todoList.Id)">
                        <div class="accordion-body">
                            <div class="row gy-2 gx-3 align-items-center">
                                <div class="col-auto">
                                    <form method="post" asp-controller="ToDoLists">
                                        <button type="button" class="btn btn-success btn-sm form-control" data-bs-toggle="modal" data-bs-target="#addItemModal@(todoList.Id)">
                                            Add task
                                        </button>
                                        <partial name="_AddToDoItem" model="@(new ToDoEntry { ToDoList = todoList})" />
                                    </form>
                                </div>
                                <div class="col-auto">
                                    <a class="btn btn-outline-primary btn-sm form-control" asp-action="OpenToDoList" asp-route-todoListId="@todoList.Id">
                                        Edit list
                                    </a>
                                </div>
                                <div class="col-auto">
                                    <button onclick="copyToClipboard(@(JsonConvert.SerializeObject(todoList, Formatting.Indented, new ToDoStatusJsonConverter())))"
                                            type="button" class="btn btn-outline-info btn-sm form-control">
                                        Copy list
                                    </button>
                                </div>
                                <div class="col d-flex flex-row-reverse">
                                    <div class="p-2 form-check form-switch">
                                        <input class="form-check-input" type="checkbox" id="hideListChecked"
                                               onclick="updateToDoListsVisiblityState(@todoList.Id, '@Url.Action("ChangeVisiblityState", "ToDoLists")')" checked="@todoList.IsVisible">
                                        <label class="form-check-label" for="hideListChecked">List is visible</label>
                                    </div>
                                </div>
                            </div>
                            <hr />
                            <form method="post" asp-controller="ToDoLists">
                                @{
                                    List<ToDoEntry> tasks;
                                }
                                @if (Model.ShowCompletedTasks)
                                {
                                    tasks = todoList.ToDoEntries.OrderBy(entry => entry.OrdinalNumber).ToList();
                                }
                                else
                                {
                                    tasks = todoList.ToDoEntries.Where(list => list.Status != ToDoStatus.Completed)
                                                                .OrderBy(item => item.OrdinalNumber)
                                                                .ToList();
                                }

                                @if (tasks.Count() != 0)
                                {
                                    <partial name="_ToDoItems" model="@tasks" />
                                }
                                else if (todoList.ToDoEntries.Count() == 0)
                                {
                                    <p class="fs-4 fw-lighter text-center">
                                        No tasks yet
                                    </p>
                                }
                                else
                                {
                                    <p class="fs-4 fw-lighter text-center">
                                        All tasks is completed.
                                    </p>
                                }
                            </form>
                        </div>
                    </div>
                </div>
            }
        </div>
        <br />
        @if (Model.PagingInfo.TotalPages > 1)
        {
            <pagenav page-model="@Model.PagingInfo" page-action="Index" page-classes-enabled="true"
                     page-class="page-link" page-class-normal="page-item" page-class-selected="page-item active"
                     aria-label="...">
            </pagenav>
        }
        <partial name="_CopyListToastForm" />
    </div>
</div>

todo-aspnetmvc-ui/Views/ToDoLists/OpenToDoList.cshtml
@{
    Layout = "_ToDoListsLayout";
}

@using Newtonsoft.Json;
@using todo_aspnetmvc_ui.Infrastructure

@model ToDoList

<div class="row m-1 p-1">
    <div id="todolistCreation" class="col-auto">
        <partial name="_SingleToDoListSummary" model="@Model" />
        <br />
    </div>
    <div class="col" style="background:azure">
        <div class="hstack gap-3">
            <div class="col-auto">
                <h3 for="inputToDoListTitle" class="form-label">ToDo: @Model.MainTitle</h3>
            </div>
            <div class="col-auto">
                <form asp-controller="ToDoLists" asp-action="EditToDoListTitle" method="post">
                    <input type="hidden" asp-for="Id" />
                    <button type="button" class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#edit@(Model.Id)">
                        Rename list
                    </button>
                    <partial name="_EditToDoListTitle" model="@Model" />
                </form>
            </div>
            <div class="col-auto">
                <form asp-controller="ToDoLists" asp-action="DeleteToDoList" method="post">
                    <input type="hidden" asp-for="Id" />
                    <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#removeTodoListModal">
                        Delete list
                    </button>
                    <dlg id="removeTodoListModal" title="Remove ToDo list">
                        Are you sure to want to completely remove this ToDo list?
                    </dlg>
                </form>
            </div>
            <div class="col-auto">
                <button onclick="copyToClipboard(@(JsonConvert.SerializeObject(Model, Formatting.Indented, new ToDoStatusJsonConverter())))"
                        type="button" class="btn btn-info btn-sm form-control">
                    Copy list
                </button>
            </div>
        </div>
        <hr class="hr" />
        @if (Model.ToDoEntries.Count != 0)
        {
            <div class="col-auto">
                <form method="post" asp-controller="ToDoLists" autocomplete="off">
                    <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addItemModal@(Model.Id)">
                        Add task
                    </button>
                    <partial name="_AddToDoItem" model="@(new ToDoEntry { ToDoList = Model})" />
                </form>
            </div>
            <div class="mb-3 form-check">
                <partial name="_ToDoItemsInfo" model="@Model.ToDoEntries" />
            </div>
        }
        else
        {
            <div class="d-flex justify-content-center flex-column">
                <p class="fs-4 fw-lighter text-center">
                    No tasks yet
                </p>
                <div class="container">
                    <div class="row">
                        <div class="col text-center">
                            <form method="post" asp-controller="ToDoLists">
                                <button type="button" class="btn btn-success btn-sm" data-bs-toggle="modal" data-bs-target="#addItemModal@(Model.Id)">
                                    Add task
                                </button>
                                <partial name="_AddToDoItem" model="@(new ToDoEntry { ToDoList = Model})" />
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        }
        <hr class="hr" />
        <a class="btn btn-primary" href="Index">Finish -></a>
    </div>
    <partial name="_CopyListToastForm" />
</div>

todo-aspnetmvc-ui/Views/ToDoLists/_ToDoItemsInfo.cshtml
@using todo_aspnetmvc_ui.Infrastructure
@using System.ComponentModel.DataAnnotations;
@using Newtonsoft.Json;

@model IEnumerable<ToDoEntry>

@{
    var orderedToDoItems = Model.OrderBy(entry => entry.OrdinalNumber);
}

<div>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Due date</th>
                <th scope="col">Status</th>
                <th scope="col">Description</th>
                <th scope="col">Notes</th>
                <th scope="col">Created at</th>
                <th scope="auto">Actions</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var todoItem in orderedToDoItems)
            {
                var dueDateInDays = (todoItem.DueDate.Value.Date - DateTime.Now.Date).TotalDays;
                string dueDateInDaysToView = "today";

                if (dueDateInDays > 0)
                {
                    dueDateInDaysToView = $"in {dueDateInDays} " + (dueDateInDays != 1 ? "days" : "day");
                }
                else if (dueDateInDays < 0)
                {
                    dueDateInDaysToView = $"{dueDateInDays * -1} " + (dueDateInDays != 1 ? "days" : "day") + " overdue";
                }
                <tr>
                    <th scope="row">@todoItem.OrdinalNumber</th>
                    <td>@todoItem.Title</td>
                    <td>
                        <div class="col">
                            <div class="row">
                                @todoItem.DueDate.Value.ToString("dd.MM.yyyy H:mm")
                            </div>
                            @if (todoItem.Status != ToDoStatus.Completed)
                            {
                                <div class="row">
                                    (@dueDateInDaysToView)
                                </div>
                            }
                        </div>
                    </td>
                    <td>
                        @if (todoItem.Status == ToDoStatus.NotStarted)
                        {
                            <img id="statusImg@(todoItem.Id)" width="20" src="~/img/icons/status-not-started.png">
                        }
                        else if (todoItem.Status == ToDoStatus.InProgress)
                        {
                            <img id="statusImg@(todoItem.Id)" width="20" src="~/img/icons/status-in-progress.png">
                        }
                        else
                        {
                            <img id="statusImg@(todoItem.Id)" width="20" src="~/img/icons/status-completed.png">
                        }
                        <span id="statusSpan@(todoItem.Id)">
                            @(todoItem.Status.GetAttribute<DisplayAttribute>().Name)
                        </span>
                    </td>
                    <td>@(string.IsNullOrEmpty(todoItem.Description) ? "-" : todoItem.Description)</td>
                    <td>@(string.IsNullOrEmpty(todoItem.Notes) ? "-" : todoItem.Notes)</td>
                    <td>@todoItem.CreationDate</td>
                    <td>
                        <button type="button" class="btn btn-outline-primary btn-sm" data-bs-toggle="modal" data-bs-target="#editItem@(todoItem.Id)">
                            Edit
                        </button>
                        <partial name="_EditToDoItem" model="@todoItem" />
                        <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#removeItem@(todoItem.Id)">
                            Remove
                        </button>
                        <form method="post" asp-controller="ToDoLists" asp-action="DeleteToDoItem">
                            <input type="hidden" asp-for="@todoItem.Id" />
                            <input type="hidden" name="todoListId" value="@todoItem.ToDoList.Id" />
                            <dlg id="removeItem@(todoItem.Id)" title="Remove ToDo item">
                                Are you sure to want to completely remove this ToDo item?
                            </dlg>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>